import type { Metadata } from "next";
import { LegalLayout, LegalSection, CONTACT_EMAIL } from "@/components/LegalLayout";

export const metadata: Metadata = {
  title: "Privacy Policy — Gimme",
  description: "Privacy Policy for the Gimme wishlist app.",
};

const LAST_UPDATED = "April 8, 2026";

export default function PrivacyPage() {
  return (
    <LegalLayout
      eyebrow="Legal"
      title="Privacy Policy"
      subtitle={`Last updated: ${LAST_UPDATED}`}
    >
      <LegalSection>
        <p>
          Gimme (&ldquo;the App&rdquo;) is a personal wishlist manager built
          by Dmytro Yaremchuk (&ldquo;we&rdquo;, &ldquo;us&rdquo;,
          &ldquo;our&rdquo;). This Privacy Policy explains what information
          we collect, how we use it, and the choices you have.
        </p>
        <p>
          By using the App you agree to the practices described here. If you
          disagree, please stop using the App and delete it from your device.
        </p>
      </LegalSection>

      <LegalSection title="1. Local-Only Mode">
        <p>
          The App works fully offline without creating an account. In
          local-only mode <strong style={{ color: "var(--l-text)" }}>no personal
          information leaves your device</strong>. All wishlist data is stored
          exclusively in SwiftData on your iPhone.
        </p>
      </LegalSection>

      <LegalSection title="2. Account &amp; Authentication">
        <p>
          You may optionally create an account to sync your wishlists across
          devices. Authentication is powered by{" "}
          <a href="https://supabase.com/privacy" target="_blank" rel="noopener noreferrer"
            style={{ color: "var(--l-accent)" }} className="hover:underline">
            Supabase
          </a>, our backend provider. When you sign up we collect:
        </p>
        <ul className="list-disc list-inside space-y-1.5 pl-1">
          <li>Your <strong style={{ color: "var(--l-text)" }}>email address</strong> (for authentication and password resets)</li>
          <li>A <strong style={{ color: "var(--l-text)" }}>user ID</strong> generated by Supabase (to link data to your account)</li>
        </ul>
        <p>
          You may also sign in with <strong style={{ color: "var(--l-text)" }}>Sign in with Apple</strong>,
          in which case Apple may share a relay email address instead of your real one.
          We never receive your Apple ID password.
        </p>
        <p>
          We do not sell, rent, or share your email address with third parties for marketing.
        </p>
      </LegalSection>

      <LegalSection title="3. Wishlist &amp; Item Data">
        <p>
          When signed in, your wishlist and item data (names, notes, URLs, prices, images)
          is stored in Supabase&apos;s cloud database to enable sync. This data is:
        </p>
        <ul className="list-disc list-inside space-y-1.5 pl-1">
          <li>Accessible only to you, protected by Row Level Security</li>
          <li>Stored in the EU region (Supabase Frankfurt)</li>
          <li>Deleted from the server when you delete your account</li>
        </ul>
        <p>
          When you <strong style={{ color: "var(--l-text)" }}>share a wishlist</strong>,
          the list and its items become publicly readable by anyone with the share link.
          You can revoke sharing at any time from the app.
        </p>
      </LegalSection>

      <LegalSection title="4. Photos &amp; Camera">
        <p>
          The App may request access to your camera and photo library to let you add
          images to items. Photos are stored locally and, if signed in, uploaded to
          Supabase Storage for sync. We do not scan, analyse, or share your photos.
        </p>
        <p>
          You can revoke access at any time in <strong style={{ color: "var(--l-text)" }}>
          Settings &rarr; Privacy &amp; Security</strong>.
        </p>
      </LegalSection>

      <LegalSection title="5. Notifications">
        <p>
          The App sends <strong style={{ color: "var(--l-text)" }}>local notifications</strong> to
          remind you of wishlist item deadlines. These are generated on your device and
          do not involve any remote servers.
        </p>
      </LegalSection>

      <LegalSection title="6. In-App Purchases">
        <p>
          Gimme Pro is a one-time purchase processed entirely by Apple via StoreKit 2.
          We do not receive or store your payment details.{" "}
          <a href="https://www.apple.com/legal/privacy/" target="_blank" rel="noopener noreferrer"
            style={{ color: "var(--l-accent)" }} className="hover:underline">
            Apple&apos;s Privacy Policy
          </a>{" "}governs payment data.
        </p>
      </LegalSection>

      <LegalSection title="7. Share Extension">
        <p>
          The Share Extension (&ldquo;Save to Gimme&rdquo;) passes URLs directly to the
          main app via a shared App Group container on your device. No URL data is sent
          to our servers except as part of an item you explicitly save while signed in.
        </p>
      </LegalSection>

      <LegalSection title="8. Analytics &amp; Crash Reporting">
        <p>
          The App does <strong style={{ color: "var(--l-text)" }}>not</strong> include
          any third-party analytics SDKs. We do not track how you use the App.
        </p>
        <p>
          Apple may collect anonymised crash reports if you have opted in to share
          diagnostics in your iOS settings. We use this data solely to fix bugs.
        </p>
      </LegalSection>

      <LegalSection title="9. Data Retention &amp; Deletion">
        <p>
          You can delete all cloud data by using the &ldquo;Delete Account&rdquo; option in Settings,
          or by emailing{" "}
          <a href={`mailto:${CONTACT_EMAIL}`} style={{ color: "var(--l-accent)" }} className="hover:underline">
            {CONTACT_EMAIL}
          </a>. We process deletion requests within 30 days.
        </p>
      </LegalSection>

      <LegalSection title="10. Children&apos;s Privacy">
        <p>
          The App is not directed at children under 13. We do not knowingly collect
          personal information from children. If you believe we have, please contact
          us and we will delete it promptly.
        </p>
      </LegalSection>

      <LegalSection title="11. Changes to This Policy">
        <p>
          We may update this Privacy Policy from time to time. We will post the revised
          version here with an updated date. Continued use after changes constitutes acceptance.
        </p>
      </LegalSection>

      <LegalSection title="12. Contact Us">
        <p>
          Questions about this Privacy Policy? Email us at{" "}
          <a href={`mailto:${CONTACT_EMAIL}`} style={{ color: "var(--l-accent)" }} className="hover:underline">
            {CONTACT_EMAIL}
          </a>
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
